---
# tasks file for rpi-unifi
- name: Install dependencies.
  apt:
    name:
      - openjdk-8-jre-headless
      - rng-tools
      - ca-certificates
      - apt-transport-https
    state: present

- name: Configure rng-tools.
  lineinfile:
    path: /etc/default/rng-tools
    regexp: '^#HRNGDEVICE=/dev/hwrng'
    line: 'HRNGDEVICE=/dev/hwrng'
    state: present
  notify: 'Restart rng-tools.'

- name: Add unifi repo gpg key.
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 06E85760C0A52C50
    state: present

- name: Add ubiquiti repo.
  apt_repository:
    repo: 'deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti'
    filename: 100-ubnt-unifi.list
    update_cache: true
    state: present

- name: Install unifi controller.
  apt:
    name: unifi
    state: present
    allow_unauthenticated: true
    update_cache: true
    autoclean: true
    autoremove: true
  notify: 'Restart unifi controller.'

- name: Start unifi controller.
  service:
    name: unifi
    state: started
    enabled: true
